### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by PachoDev** [RockyLogic/Discord-Link-Opener#1]
HIi i want the code to work but its impossible

**Comment by RockyLogic** [comment]
Hi, just ran the program everything seemed fine, make sure to have edited the Channel ID text file, replace the token in the main.py and have discord.py installed. 

I just retried it after seeing your issue, it seems fine on my end. I'll look into it if the issue persists.

![image](https://user-images.githubusercontent.com/56990368/80395723-a1818480-8881-11ea-914f-e678504ddf68.png)
![image](https://user-images.githubusercontent.com/56990368/80395751-a9d9bf80-8881-11ea-8491-c82e1f510bb4.png)

**Comment by tesosuhvbuovboeruvb** [comment]
Doesn't seem to open links if they are sent through a webhook?

**Comment by RockyLogic** [comment]
yeah made it just for text messages, you can change it for embeds if you take a look at discord.py documentation for embeds, they have titles, fields and description, and each server can send the link to different parts of the embed, some groups set it as the description some set it as a field.

**Comment by dowehavet0** [comment]
appriciate the effort but can not use due to embedded messages, can you make an update so that it can open in any of these cases you tell. I would do it but i have no idea about programming

**Comment by agentzz1** [comment]
@client.event
async def on_message(message):
    if message.channel.id in channelList:
        await asyncio.sleep(0.3)
        last_msg = await get_last_msg(message.channel.id)
        fields = last_msg.embeds[0].fields
        linkembed = next(x for x in fields if x.name == "Link")
        urls = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*(),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', linkembed.value if linkembed else "")
        for url in urls:
            await open_url(url)

**Comment by agentzz1** [comment]
this is a fix from a discord server but i dont how to implement it

**Comment by agentzz1** [comment]
i think you paste it line 29 but it is not working for me tho

**Comment by RockyLogic** [comment]
Discord has updated to the API/V9, from the original V6. This project is still using the V6 API, plans have yet to be made regarding updating the project.
