### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by ktmyname** [RockyLogic/Discord-Link-Opener#2]
If anyone know whats wrong with this or have any alternative way to do this task please comment.

i added the token and channel ID. but the link doesn't open. i've tested this by using my other discord account to send me link but the link doesn't open . 
![Capture](https://user-images.githubusercontent.com/79153588/108079236-8416e480-7066-11eb-9271-0928c398ea1f.PNG)

**Comment by RockyLogic** [comment]
Discord has updated to the API/V9, from the original V6. This project is still using the V6 API, plans have yet to be made regarding updating the project. Not sure if the new API affects the functionality of the program, but this may be the problem for the issues
